# Generated by Django 3.1.2 on 2020-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201022_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
