# Generated by Django 3.1.6 on 2021-02-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
