# Generated by Django 3.1.6 on 2021-05-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210307_0519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
